---
- name: Assert on 'deploy.dest'
  assert: { that: "(deploy.dest is defined and deploy.dest is not none and deploy.dest | trim != '')" }
  tags: ['deploy', 'chef', 'chef_solo', 'chef_assert_dest']

- name: Assert on 'chef.run_list'
  assert: { that: "(chef.run_list is defined and chef.run_list is not none and chef.run_list | trim != '')" }
  tags: ['deploy', 'chef', 'chef_solo', 'chef_assert_tmp_dir']

- name: Run Chef (Solo)
  command: "chef-solo --format min --no-fork --no-color --config /etc/chef/solo.rb -o '{{ chef.run_list }}'"
  args:
    chdir: "{{ deploy.dest }}"
  become: "{{ chef.with_sudo|default(omit) }}"
  register: run_chef
  tags: ['deploy', 'chef', 'chef_solo', 'chef_run']
