---
# TODO: assertion
- name: Update Gem system
  command: gem update --system --no-document
  become: yes
  tags: [deploy, ruby, gem, gem_update, gem_update_system]

- name: Update Gems
  command: gem update --env-shebang --no-document --conservative
  delay: 3
  retries: 2
  become: "{{ deploy.gem.with_sudo|default(omit) }}"
  tags: [deploy, ruby, gem, gem_update]

- name: Install or Upgrade Gem
  gem:
    name: "{{ gem_name }}"
    state: latest
  with_items: "{{ deploy.gem.packages|default(['bundler']) }}"
  loop_control:
    loop_var: gem_name
  when: deploy.gem.packages is defined
  become: "{{ deploy.gem.with_sudo|default(omit) }}"
  delay: 3
  retries: 2
  tags: [deploy, ruby, gem, gem_install]
