---
- name: Install git
  package:
    name: git
    state: latest
  tags: [deploy, git, git_install]

- name: Create known_hosts file
  file:
    path: ~/.ssh/known_hosts
    owner: "{{ ansible_user }}"
    mode: 0600
    state: touch
  tags: [deploy, git, git_known_hosts]

# TODO: improve robustness
- name: Add repo key to known_hosts
  shell: "ssh-keyscan -H -t dsa {{ git.server }} >> ~/.ssh/known_hosts"
  no_log: True
  when: git.server is defined
  tags: [deploy, git, git_ssh_keyscan]

# FIXME: pass update. that a bug?
- name: Clone project
  git:
    accept_hostkey: "{{ git.accept_hostkey|default(omit) }}"
    depth: "{{ git.depth|default(omit) }}"
    dest: "{{ git.dest }}"
    force: "{{ git.force|default(True) }}"
    repo: "{{ git.repo }}"
    update: True
    version: "{{ git.version|default(omit) }}"
  register: git_clone
  tags: [deploy, git, git_clone]
