---
- name: Assert on 'git.dest'
  assert: { that: "(git.dest is defined and git.dest is not none and git.dest | trim != '')" }
  tags: ['deploy', 'git', 'git_assert_dest']

- name: Assert on 'git.repo'
  assert: { that: "(git.repo is defined and git.repo is not none and git.repo | trim != '')" }
  tags: ['deploy', 'git', 'git_assert_repo']

- name: Install Git
  package:
    name: git
    state: latest
  tags: [deploy, git, git_install]

- name: Create known_hosts file
  file:
    path: ~/.ssh/known_hosts
    owner: "{{ ansible_user }}"
    mode: 0600
    state: touch
  tags: [deploy, git, git_known_hosts]

# TODO: improve robustness
- name: Add repo key to known_hosts
  shell: "ssh-keyscan -H -t dsa {{ git.server }} >> ~/.ssh/known_hosts"
  no_log: yes
  when: git.server is defined
  tags: [deploy, git, git_ssh_keyscan]

# FIXME: pass update. that a bug?
- name: Clone project
  git:
    accept_hostkey: "{{ git.accept_hostkey|default(omit) }}"
    depth: "{{ git.depth|default(omit) }}"
    dest: "{{ git.dest }}"
    force: "{{ git.force|default('yes') }}"
    repo: "{{ git.repo }}"
    update: yes
    version: "{{ git.version|default(omit) }}"
  register: git_clone
  delay: 5
  retries: 2
  tags: [deploy, git, git_clone]
