---
- name: Remove Packages
  apt:
    name: "{{ remove_name }}"
    autoremove: yes
    purge: yes
    state: absent
  become: yes
  register: packages_remove
  with_items: "{{ deploy.packages.remove|default({}) }}"
  loop_control:
    loop_var: remove_name
  when: (deploy.packages.remove is defined and deploy.packages.remove is not none and deploy.packages.remove | trim != '')
  tags: [deploy, packages, packages_remove]

- name: Install Packages
  apt:
    name: "{{ install_name }}"
    autoremove: yes
    dpkg_options: 'force-confold,force-confdef,force-confmiss'
    state: latest
  become: yes
  register: packages_install
  with_items: "{{ deploy.packages.install|default({}) }}"
  loop_control:
    loop_var: install_name
  when: (deploy.packages.install is defined and deploy.packages.install is not none and deploy.packages.install | trim != '')
  delay: 5
  retries: 2
  tags: [deploy, packages, packages_install]
