---
- name: Resolve pip requirements
  pip:
    virtualenv: "{{ deploy.pip.virtualenv|default(omit) }}"
    requirements: "{{ deploy.pip.requirements }}"
    state: latest
  become: "{{ deploy.pip.with_sudo|default(omit) }}"
  when: deploy.pip.requirements is defined
  delay: 5
  retries: 2
  tags: [deploy, python, pip, pip_requiremenets]

- name: Install pip Packages
  pip:
    name: "{{ pip_name }}"
    virtualenv: "{{ deploy.pip.virtualenv|default(omit) }}"
    state: latest
  with_items: "{{ deploy.pip.packages }}"
  loop_control:
    loop_var: pip_name
  become: "{{ deploy.pip.with_sudo|default(omit) }}"
  when: deploy.pip.packages is defined
  delay: 5
  retries: 2
  tags: [deploy, python, pip, pip_packages]
