- name: Run Chef (Solo)
  command: "chef-solo --no-fork --no-color -c /etc/chef/solo.rb -o '{{ chef.run_list }}'"
  args:
    chdir: "{{ deploy.target }}"
  become: "{{ chef.with_sudo|default(omit) }}"
  register: run_chef
  tags: ['deploy', 'chef', 'chef_run', 'chef_client']
