-   name: Update Rubygems
    command: gem update --system --no-document
    register: gem_update_system
    changed_when: gem_update_system.stdout.find('Successfully installed') != -1
    become: true
    tags:
    - ruby
    - gem
    - gem_update
    - gem_update_system
-   name: Update Gems
    command: gem update --env-shebang --no-document --conservative
    register: gem_update
    changed_when: gem_update.stdout.find('Successfully installed') != -1
    become: '{{ data.with_sudo|default(omit) }}'
    tags:
    - ruby
    - gem
    - gem_update
-   name: List of Gems to install
    debug: var=data.packages verbosity=3
    when: data.packages is defined
-   name: Install or Upgrade Gems
    gem:
        name: '{{ gem_name }}'
        state: latest
        build_flags: -j{{ ansible_processor_vcpus|default('1') }}
    with_items: '{{ data.packages|default([''bundler'']) }}'
    loop_control:
        loop_var: gem_name
    register: gem_install
    become: '{{ data.with_sudo|default(omit) }}'
    when: data.packages is defined
    tags:
    - ruby
    - gem
    - gem_install
