-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 6b1aa19425b35f8c34f43ada8f1045b028dc19a5
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: codevalidator
        name: Codevalidator
        language: script
        description: Simple source code validator with file reformatting option
        files: .*\.(yml|yaml|py|rb|erb|sql)$|Vagrantfile$
        entry: pre-commit-hooks/codevalidator.sh
    -   id: bashate
        name: bashate
        language: script
        description: A pep8 equivalent for bash scripts
        files: .*\.(sh|bash)$
        entry: pre-commit-hooks/bashate.sh
    -   id: shellcheck
        name: ShellCheck
        language: script
        description: Static analysis tool for shell scripts in the name are encrypted
        files: .*\.(sh|bash)$
        entry: pre-commit-hooks/shellcheck.sh
    -   id: ansible-lint
        name: Ansible Lint
        language: script
        description: Best practices checker for Ansible
        files: taxigirl\.yml$
        entry: pre-commit-hooks/ansible-lint.sh
    -   id: vault
        name: Ansible Vault Check
        language: script
        description: Pre-commit hook that verifies if all files containing 'vault'
            in the name are encrypted
        files: .*vault.*\.(yml|yaml)$
        entry: pre-commit-hooks/vault.sh
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: d044ff27300a6dc8b1a56cd22552e3a810dc6f49
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: 316b795b2f32cbe80047aff7e842b72368d5a2c1
    hooks:
    -   id: yapf
-   repo: git://github.com/guykisel/prospector-mirror
    sha: 00fbd80101566b1b9c873c71f2ab7b95b8bd0a7d
    hooks:
    -   id: prospector
        args:
        - --max-line-length=160
        - --no-autodetect
        - --strictness=medium
#        - --without-tool=pep257
#        - --without-tool=pylint
# -   repo: git://github.com/jordant/rubocop-pre-commit-hook
#     sha: ae431551f703fff928bfabe2b440a9a8048e962b
#     hooks:
#     -   id: check-rubocop
#         files: .*\.rb$|Vagrantfile$
# -   repo: https://github.com/therealjessesanford/reek-pre-commit-hook.git
#     sha: 68381b2db41db5221d04881d8054b8f7da55c8e7
#     hooks:
#     -   id: check-reek
#         files: .*\.rb$
# -   repo: git://github.com/chriskuehl/puppet-pre-commit-hooks
#     sha: 4bc20784cca4713e2ba5f884ff4c37a1e4e87de1
#     hooks:
#     -   id: erb-validate
#         files: .*\.erb$
