---
language: 'python'

python: '2.7'
# matrix:
#   include:
#     - python: '2.7'
#       env: TEST_SUITE=suite_2_7
#     - python: '3.5'
#       env: TEST_SUITE=suite_3_5

virtualenv:
  system_site_packages: True

git:
  depth: 1

env:
  - ANSIBLE_INVENTORY_FILE=inventory/travis.ini TAXIGIRL_CONFIG=@config/test.yml

before_install:
#  - 'sudo apt-get update -y'

install:
  - 'sudo apt-get install -y curl'

script:
  - 'pwd; ls'
#  - 'git clone --depth 1 https://github.com/nickjj/rolespec'
#  - 'cd rolespec ; bin/rolespec -r https://github.com/gretel/taxigirl'
  - 'make install'
  - 'make ansible-test'
