---
cache:
  bundler: true
  pip: true
  ccache: true
  directories:
  - vendor/cache

git:
  depth: 1

env:
  global:
  - TAXIGIRL_EXTRA_ARGS=@./config/test.yml
  - TAXIGIRL_INVENTORY_PATH=./inventory/travis.ini
  - TAXIGIRL_LIMIT=local
  - TAXIGIRL_PLAYBOOK=./playbooks/main.yml
  - TAXIGIRL_VERBOSE=vv

matrix:
  include:
  - os: linux
    env: TOXENV=py27
    language: python
    python: 2.7.11
  - os: linux
    dist: trusty
    env: TOXENV=py27
    language: python
    python: 2.7.11
    sudo: required
  - os: linux
    dist: trusty
    env: PYTHON_VERSION=3.5.1 PIP_BIN_NAME=pip3 TOXENV=py35
    language: python
    python: 3.5.1
    sudo: required
  - os: osx
    env: TOXENV=py27 CC=clang
    language: generic
    sudo: required

virtualenv:
  system_site_packages: False

before_install:
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y -qq update; fi'
#- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y -qq upgrade; fi'
#- 'git clone --depth 1 https://github.com/nickjj/rolespec'
#- 'cd rolespec; bin/rolespec -h'

install:
- 'uname -a; which python'

script:
- 'pwd; ls -la'
- 'make install'
- 'make ansible-run'
