---
language: 'python'
cache:
  - bundler
  - pip
  - directories:
    - bin
    - files
    - lib

python: '2.7.11'
# matrix:
#   include:
#     - python: '2.7.11'
#       env: TEST_SUITE=suite_2_7
#     - python: '3.5'
#       env: TEST_SUITE=suite_3_5

virtualenv:
  system_site_packages: False

git:
  depth: 1

env:
  - ANSIBLE_INVENTORY_FILE=inventory/travis.ini TAXIGIRL_CONFIG=@config/test.yml

before_install:
#  - 'sudo apt-get update -y'
#  - 'sudo apt-get upgrade -y'
  - 'which python'

install:
  - 'sudo apt-get install -y curl'

script:
  - 'pwd; ls -la'
#  - 'git clone --depth 1 https://github.com/nickjj/rolespec'
#  - 'cd rolespec ; bin/rolespec -r https://github.com/gretel/taxigirl'
  - 'make install'
  - 'make ansible-run'
