-   name: 'Playbook: Galaxy'
    any_errors_fatal: true
    become: true
    gather_facts: true
    hosts: "{{ hosts|default('all') }}"
    vars_files:
    - ../vars/galaxy.yml
    roles:
    -   role: switch-apt-mirror
        when: (ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu') and (galaxy.roles.switch_apt_mirror is defined and galaxy.roles.switch_apt_mirror == True)
    -   role: os-hardening
        when: (ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu') and (galaxy.roles.os_hardening is defined and galaxy.roles.os_hardening == True)
    -   role: ntp
        when: (ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu') and (galaxy.roles.ntp is defined and galaxy.roles.ntp == True)
    -   role: unattended-upgrades
        when: (ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu') and (galaxy.roles.unattended_upgrades is defined) and (galaxy.roles.unattended_upgrades == True)
    post_tasks:
    -   name: Flag Completion
        set_fact: completed_galaxy=true
