-   name: 'Playbook: Service'
    hosts: "{{ hosts|default('all') }}"
    gather_facts: true
    any_errors_fatal: true
    strategy: "{{ strategy|default('linear') }}"
    pre_tasks:
    - name: Meditate on Service
      pause: prompt="Take a deep breath." seconds=5
      tags:
      - service
      - pause
    roles:
    -   role: permissions
        chdir: "{{ deploy.dest }}"
        when: (deploy.dest is defined)
    -   role: run_chef
        chdir: "{{ deploy.dest }}"
        when: ('chef' in service.tasks)
    post_tasks:
    -   name: Flag Completion
        set_fact: completed_service=true
        tags:
        - service
        - service_fact
    -   name: Notification
        local_action:
            module: slack
            token: "{{ slack.token }}"
            msg: Service done
            username: "Taxigirl on {{ inventory_hostname }}"
            attachments:
            -   title: Configuration
                text: "{{ service }}"
                color: good
                footer: "{{ ansible_version }}"
                # fields:
                # -   title: Configuration (Deploy)
                #     value: "{{ deploy|to_nice_yaml }}"
                #     short: no
                # -   title: Facts
                #     value: "{{ hostvars[inventory_hostname]|to_nice_yaml }}"
                #     short: no
        when: slack.token is defined
        tags:
        - service
        - slack
        - service_slack
