-   name: 'Debug: data'
    debug: var=data verbosity=3
    tags:
    - debug
    - python
    - pip
    - pip_debug
-   name: Resolve pip requirements
    pip:
        virtualenv: "{{ data.virtualenv|default(omit) }}"
        requirements: "{{ data.requirements }}"
        state: latest
    become: "{{ data.with_sudo|default(omit) }}"
    when: data.requirements is defined
    tags:
    - python
    - pip
    - pip_requiremenets
-   name: Install pip Packages
    pip:
        name: "{{ install_pip }}"
        virtualenv: "{{ data.virtualenv|default(omit) }}"
        state: latest
    with_items: "{{ data.packages }}"
    loop_control:
        loop_var: install_pip
    become: "{{ data.with_sudo|default(omit) }}"
    when: data.packages is defined
    tags:
    - python
    - pip
    - pip_install
# -   name: Add binstubs to PATH
#     lineinfile: >
#         dest=/etc/environment
#         state=present
#         backrefs=yes
#         regexp='PATH=(["]*)((?!.*?{{ data.virtualenv }}/bin).*?)(["]*)$'
#         line="PATH=\1{{ data.virtualenv }}/bin:\2\3"
#     become: yes
#     when: (data.virtualenv is defined)
#     tags:
#     - pip
#     - pip_path
