---
- name: Update APT Cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt.cache_valid_time|default('3600') }}"
  register: 'apt_update'
  become: yes
  delay: '5'
  retries: '2'
  tags: [provision, debian, apt, apt_update]

- name: Install Aptitude
  apt:
    name: 'aptitude'
    state: 'present'
  register: 'apt_aptitude'
  become: yes
  when: (apt.install_aptitude is defined) and (apt.install_aptitude == True)
  tags: [provision, debian, apt, apt_aptitude]

- name: Upgrade APT packages
  apt:
    upgrade: "{{ apt.upgrade|default('yes') }}"
    dpkg_options: "{{ apt.dpkg_options|default('force-confold,force-confdef,force-confmiss') }}"
    autoremove: "{{ apt.autoremove|default('yes') }}"
    install_recommends: "{{ apt.install_recommends|default('no') }}"
  register: 'apt_upgrade'
  become: yes
  when: apt_update.cache_updated
  retries: '2'
  tags: [provision, capt, apt_update, apt_upgrade]
