---
- name: EC2
  include: provision_ec2.yml
  when: hosts == 'ec2'

# TODO
# - name: EC2 RDS
#   include: ec2_rds.yml
#   when: hosts == 'ec2'

- name: Local
  include: provision_local.yml
  when: hosts == 'local'

- name: Bootstrap Debian-style
  include: bootstrap_debian.yml
  become: True
  when: (ansible_os_family == 'Debian') or (ansible_os_family == 'Ubuntu')

- name: Include Task
  include: ../roles/provision/tasks/{{ inc_p_task }}.yml
  with_items: "{{ provision.tasks }}"
  loop_control:
    loop_var: inc_p_task
  when: (provision.tasks is defined and provision.tasks is not none and provision.tasks | trim != '')
