---
- name: Assert on 'version'
  assert: { that: "(version is defined and version is not none and version | trim != '' and version != '0.0.0')" }
  tags: [provision, provision_assert_version]

- name: Assert on 'deploy.dest'
  assert: { that: "(deploy.dest is defined and deploy.dest is not none and deploy.dest | trim != '')" }
  tags: [provision, provision_assert_dest]

- name: Bootstrap Debian System
  include: _debian_bootstrap.yml
  when: (ansible_os_family == 'Debian') or (ansible_os_family == 'Ubuntu')
  tags: [provision, debian, provision_debian]

- name: Create base directory
  file:
    path: "{{ deploy.dest }}"
    recurse: True
    owner: "{{ ansible_user }}"
    mode: 0755
    state: directory
  become: yes
  tags: [provision, provision_base_directory]

- name: Include Task
  include: ../roles/provision/tasks/{{ inc_p_task }}.yml
  with_items: "{{ provision.tasks }}"
  loop_control:
    loop_var: inc_p_task
  when: (provision.tasks is defined and provision.tasks is not none and provision.tasks | trim != '')
  tags: [provision, provision_include_task]
