---
- name: Wait for SSH to be reachable
  wait_for: host="{{ ansible_ssh_host }}" port="{{ ansible_ssh_port }}"
  delegate_to: localhost
  tags: [provision, local, local_waitfor]

# # TODO check
# - name: Remove require tty
#   lineinfile: regexp="^\s+\w+\s+requiretty" dest=/etc/sudoers state=absent
#   become: True
#   ignore_errors: True
#  tags: [provision, local, local_requiretty]

- name: Send notification to Slack
  slack:
    token: "{{ slack.token }}"
    msg: "Created instance(s)"
    attachments:
      - title: "Info"
        text: "{{ ansible_hostname }}"
        color: "#00ff00"
        fields:
          - title: "FQDN"
            value: "{{ ansible_fqdn }}"
            short: "true"
          - title: "Distro"
            value: "{{ ansible_os_family }}"
            short: "true"
    username: "{{ slack.username }}"
    channel: "{{ slack.channel }}"
    icon_emoji: "{{ slack.icon_emoji }}"
  when: slack.token is defined
  tags: [provision, local, slack, slack_provision_local]
