-   name: Assert on 'chdir'
    assert:
        that: (chdir is defined and chdir is not none and chdir | trim != '')
    tags:
    - directory
    - directory_assert_chdir
-   name: Create Directory
    file:
        path: "{{ chdir }}"
        mode: 'u=rwX,g=rX,o=rX'
        owner: "{{ ansible_user }}"
        recurse: yes
        state: directory
    become: yes
    tags:
    - directory
