# -   name: Assert on 'git.dest'
#     assert:
#         that: (git.dest is defined and git.dest is not none and git.dest | trim != '')
#     tags:
#     - deploy
#     - deploy_assert_dest
-   name: Create Deployment directory II
    file:
        path: '{{ deploy.dest }}'
        recurse: true
        owner: '{{ ansible_user }}'
        mode: 0775
        state: directory
    become: yes
    tags:
    - deploy
    - deploy_dest
# -   name: Include Deployment Task
#     include: roles/deploy/tasks/{{ deploy_task }}.yml
#     with_items: '{{ deploy.tasks }}'
#     loop_control:
#         loop_var: deploy_task
#     when: (deploy.tasks is defined and deploy.tasks is not none and deploy.tasks | trim != '')
#     tags:
#     - deploy
#     - deploy_include
-   name: Send notification to Slack
    slack:
        token: '{{ slack.token }}'
        msg: Deployment
        attachments:
        -   title: Host
            text: '{{ ansible_default_ipv4.address }} | {{ ansible_hostname }} | {{ ansible_fqdn }}'
            color: good
            fields:
            -   title: Facts
                value: '{{ hostvars[inventory_hostname] }}'
                short: 'true'
        username: '{{ slack.username }}'
        channel: '{{ slack.channel }}'
        icon_emoji: '{{ slack.icon_emoji }}'
    when: slack.token is defined
    tags:
    - deploy
    - deploy_slack
    - slack
