---
ubuntu_apt_mirror:  "{{ galaxy.ubuntu_apt.mirror|default(omit) }}"

ntp_servers: "{{ galaxy.ntp.servers|default([ubuntu.pool.ntp.org,2.ubuntu.pool.ntp.org]) }}"

unattended_origins_patterns:
- 'origin=Ubuntu,archive=${distro_codename}-security'
- 'o=Ubuntu,a=${distro_codename}'
- 'o=Ubuntu,a=${distro_codename}-updates'
- 'o=Ubuntu,a=${distro_codename}-proposed-updates'
unattended_automatic_reboot: "{{ galaxy.unattended.automatic_reboot|default('false') }}"
unattended_automatic_reboot_time: "{{ galaxy.unattended.automatic_reboot_time|default(omit) }}"
unattended_mail: "{{ galaxy.unattended.mail|default('false') }}"
unattended_mail_only_on_error: "{{ galaxy.unattended.mail_only_on_error|default('false') }}"
unattended_minimal_steps: true

sysctl_config:
     # IPv4 traffic forwarding.
     net.ipv4.ip_forward: 1

     # IPv6 traffic forwarding.
     net.ipv6.conf.all.forwarding: 0

     # ignore RAs on Ipv6.
     net.ipv6.conf.all.accept_ra: 0
     net.ipv6.conf.default.accept_ra: 0

     # Enable RFC-recommended source validation feature.
     net.ipv4.conf.all.rp_filter: 1
     net.ipv4.conf.default.rp_filter: 1

     # Reduce the surface on SMURF attacks.
     # Make sure to ignore ECHO broadcasts, which are only required in broad network analysis.
     net.ipv4.icmp_echo_ignore_broadcasts: 1

     # There is no reason to accept bogus error responses from ICMP, so ignore them instead.
     net.ipv4.icmp_ignore_bogus_error_responses: 1

     # Limit the amount of traffic the system uses for ICMP.
     net.ipv4.icmp_ratelimit: 100

     # Adjust the ICMP ratelimit to include ping, dst unreachable,
     # source quench, ime exceed, param problem, timestamp reply, information reply
     net.ipv4.icmp_ratemask: 88089

     # Disable IPv6
     net.ipv6.conf.all.disable_ipv6: 1

     # Protect against wrapping sequence numbers at gigabit speeds
     net.ipv4.tcp_timestamps: 0

     # Define restriction level for announcing the local source IP
     net.ipv4.conf.all.arp_ignore: 1

     # Define mode for sending replies in response to
     # received ARP requests that resolve local target IP addresses
     net.ipv4.conf.all.arp_announce: 2

     # RFC 1337 fix F1
     net.ipv4.tcp_rfc1337: 1
