# -   name: Assert on 'provision.shell.commands'
#     assert:
#         that: (provision.shell.commands is defined and provision.shell.commands is not none and provision.shell.commands | trim != '')
-   name: Run shell commands
    shell: '{{ shell_command }}'
    args:
        chdir: '{{ deploy.dest }}'
    with_items: '{{ provision.shell.commands }}'
    loop_control:
        loop_var: shell_command
    register: shell_commands
    become: '{{ provision.shell.with_sudo|default(omit) }}'
    tags:
    - provision
    - shell
    - shell_commands
