-   name: Update Cache
    apt:
        update_cache: yes
        cache_valid_time: "{{ apt.cache_valid_time|default('3600') }}"
    register: apt_update
    become: yes
    tags:
    - packages
    - apt
    - apt_update
-   name: Debug
    debug: var=apt_update verbosity=3
    tags:
    - debug
    - packages
    - apt
    - apt_debug
-   name: Remove Packages
    apt:
        name: "{{ remove_apt }}"
        state: absent
        purge: yes
    become: yes
    register: packages_remove
    with_items: "{{ data.remove }}"
    loop_control:
        loop_var: remove_apt
    when: (data.remove is defined and data.remove is not none and data.remove | trim != '')
    tags:
    - packages
    - apt
    - apt_remove
-   name: Upgrade Packages
    apt:
        upgrade: "{{ apt.upgrade|default('yes') }}"
        dpkg_options: "{{ apt.dpkg_options|default('force-confold,force-confdef,force-confmiss') }}"
        autoremove: "{{ apt.autoremove|default('yes') }}"
        install_recommends: "{{ apt.install_recommends|default('no') }}"
    register: apt_upgrade
    become: yes
    # when: apt_update.cache_updated
    tags:
    - packages
    - apt
    - apt_upgrade
-   name: Install Packages
    package:
        name: "{{ install_apt }}"
        state: "{{ data.state|default('present') }}"
    become: yes
    register: packages_install
    with_items: "{{ data.install }}"
    loop_control:
        loop_var: install_apt
    when: (data.install is defined and data.install is not none and data.install | trim != '')
    tags:
    - packages
    - apt
    - apt_install
