-   name: 'Assert: data'
    assert:
        that: (data is defined and data is not none and data|trim != '')
    tags:
    - provision
    - provision_assert_data
-   name: Data
    debug: var=data verbosity=3
-   name: 'Packages: APT'
    include: apt.yml
    when: (ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu')
