---
- name: 'Assert: data'
  assert: { that: "(data is defined and data is not none and data | trim != '')" }
  tags: [destroy, ec2, ec2_assert_data]

- pause: prompt="Make sure you are OK to Terminate Instance!"
  tags: [destroy, ec2, ec2_destroy_terminate]

- name: Terminate Instance
  local_action:
    module: ec2
    state: "{{ ec2_destroy.terminate_state|default('stopped') }}"
    instance_ids: "{{ data }}"
    region: "{{ ec2.region|default('eu-west-1') }}"
    wait: yes
  register: ec2_destroy
  tags: [destroy, ec2, ec2_destroy_terminate]

- name: Send notification to Slack
  slack:
    token: "{{ slack.token }}"
    msg: "Destroyed instance(s)"
    attachments:
      - title: "Info"
        text: "{{ ec2.instance_tags.Name }}"
        color: good
        fields:
          - title: "Instance ID"
            value: "{{ id }}"
            short: "yes"
    username: "{{ slack.username }}"
    channel: "{{ slack.channel }}"
    icon_emoji: "{{ slack.icon_emoji }}"
  when: slack.token is defined
  tags: [destroy, ec2, slack, ec2_destroy_slack]
