version: 0.1.0
hosts: all
galaxy:
    enabled: false
    roles:
        os_hardening: false
        ntp: true
        switch_apt_mirror: true
        unattended_upgrades: true
    ubuntu_apt:
        mirror: 'ftp.hawo.stw.uni-erlangen.de'
provision:
    tasks:
    - bootstrap
    - packages
    packages:
        state: latest
        install:
        - build-essential
        - ca-certificates
        - curl
        - git
deploy:
    dest: /opt/chef_example
    tasks:
    - berkshelf
    - bundler
    - chef
    - gem
    - git
    - packages
    - pip
    packages:
        state: latest
        install:
        - libssl-dev
        - libreadline-dev
        - libjson-c-dev
        - libyaml-dev
        - libxml2-dev
        - libxslt1-dev
        - zlib1g-dev
        - python
        - python-dev
        - python-apt
        - python-pkg-resources
        - python-setuptools
        - virtualenv
        - ruby
        - ruby-dev
        - ruby-ffi
        - rubygems-integration
        - ruby-nokogiri
        - ruby-bundler
    gem:
        # with_sudo: true
        packages:
        - bundler
        - berkshelf
    pip:
        virtualenv: /opt/chef_example
        packages:
        - grc
service:
    tasks:
    - chef
apt:
    upgrade: dist
git:
    accept_hostkey: true
    depth: 1
    dest: /opt/chef_example/cookbooks/os-hardening
    repo: https://github.com/dev-sec/chef-os-hardening
    server: github.com
bundler:
    dest: /opt/chef_example/cookbooks/os-hardening
    binstub_directory: /opt/chef_example/bin
    clean: true
    with_sudo: true
    exclude_groups:
    - development
    - integration
    - openstack
    - test
    - tools
    extra_args: --jobs {{ ansible_processor_vcpus }}
    gem_path: /opt/chef_example/vendor/cache
berkshelf:
    dest: /opt/chef_example/cookbooks/os-hardening
    cookbook_path: /opt/chef_example/berks-cookbooks
chef:
    base_dir: /opt/chef
    config_dir: /etc/chef
    channel: current
    log_location: /tmp/chef_run.log
    run: zero
    run_list: recipe[os-hardening]
    with_sudo: true
    attributes:
        base_path: /opt/chef_example
slack: []
