version: 0.1.0
hosts: all
galaxy:
    enabled: false
    roles:
        os_hardening: false
        ntp: false
        switch_apt_mirror: true
        unattended_upgrades: false
    unattended_upgrades:
        automatic_reboot: true
apt:
    upgrade: dist
unattended_upgrades:
    automatic_reboot: true
provision:
    tasks:
    - bootstrap
    - packages
    packages:
        state: latest
        install:
        - ca-certificates
        - curl
        - build-essential
        - gcc
        - git
deploy:
    dest: /opt/test
    tasks: []
service:
    tasks: []
slack: []
