version: 0.1.0
hosts: all
galaxy:
    roles:
        os_hardening: false
        ntp: false
        switch_apt_mirror: true
        unattended_upgrades: false
apt:
    upgrade: dist
unattended_upgrades:
    automatic_reboot: true
provision:
    tasks:
    - bootstrap
    - packages
    packages:
        state: latest
        install:
        - ca-certificates
        - curl
        - build-essential
        - gcc
        - git
