version: 0.1.0
apt: {upgrade: 'no'}
deploy:
  dest: /opt/test
  packages: null
  shell:
    commands: [echo 'what a ride!' | wall]
    with_sudo: false
  tasks: [packages, shell]
provision:
  packages:
    install: [tmux]
  tasks: [packages]
roles: {ntp: true, os_hardening: false, switch_apt_mirror: true, unattended_upgrades: true}
slack: []
