hosts: 'local'
provision:
  tasks:
  - packages
  - shell
  packages:
    install:
    - build-essential
  shell:
    commands:
    - echo 'what a ride!' | wall
    with_sudo: False
deploy:
  target: '/opt/test'
  tasks:
  - packages
  - shell
  packages:
  shell:
slack: []
