version: 0.1.0
hosts: all
slack: []
galaxy:
    enabled: false
provision:
    tasks:
    - bootstrap
    - packages
    packages:
        state: latest
        install:
        - ca-certificates
        - curl
    shell:
        with_sudo: true
        commands:
        - id
        - echo 'provision'
deploy:
    tasks:
    - shell
    dest: /opt/test
    shell:
        commands:
        - id
        - echo 'deploy'
