hosts: 'local'
provision:
  tasks:
  - packages
  packages:
    install:
    - build-essential
deploy:
  dest: '/opt/test'
  tasks:
  - packages
  - shell
  packages:
  shell:
    commands:
    - echo 'what a ride!' | wall
    with_sudo: False
slack: []
