-   name: Assert on 'chdir'
    assert:
        that: (chdir is defined and chdir is not none and chdir | trim != '')
    tags:
    - chef
    - berkshelf
    - berkshelf_assert
-   name: Run Berkshelf
    command: bundle exec berks vendor {{ berkshelf.cookbook_path }}
    args:
        chdir: "{{ chdir }}"
    register: run_berkshelf
    changed_when: run_berkshelf.stdout.find('Nothing to update') != -1
    when: berkshelf.cookbook_path is defined
    become: "{{ berkshelf.with_sudo|default(omit) }}"
    tags:
    - chef
    - berkshelf
    - berkshelf_run
