-   name: 'Assert: ec2_destroy.instance_ids'
    assert:
        that: (ec2_destroy.instance_ids is defined and ec2_destroy.instance_ids is not none and ec2_destroy.instance_ids | trim != '')
    tags:
    - destroy
    - aws_ec2
    - aws_ec2_destroy
    - aws_ec2_destroy_assert
-   name: Confirm Termination
    pause: prompt="Make sure you are OK to Terminate Instance!"
    tags:
    - destroy
    - aws_ec2
    - aws_ec2_destroy
    - aws_ec2_destroy_pause
-   name: Terminate Instance
    local_action:
        module: ec2
        state: "{{ ec2_destroy.terminate_state|default('stopped') }}"
        instance_ids: "{{ ec2_destroy.instance_ids }}"
        region: "{{ ec2.region|default('eu-central-1') }}"
        wait: true
    register: ec2_destroy
    tags:
    - destroy
    - aws_ec2
    - aws_ec2_destroy
    - aws_ec2_destroy_terminate
-   name: Notification
    local_action:
        module: slack
        token: "{{ slack.token }}"
        msg: Destruction
        username: "Taxigirl on {{ inventory_hostname }}"
        attachments:
        -   title: Host
            text: "{{ ansible_fqdn }}"
            color: warning
            fields:
            -   title: Instance
                value: "{{ ec2_destroy.instance_ids }}"
                short: yes
    when: slack.token is defined
    tags:
    - destroy
    - aws_ec2
    - aws_ec2_destroy
    - aws_ec2_destroy_slack
    - slack
