-   name: Assert on 'chdir'
    assert:
        that: (chdir is defined and chdir is not none and chdir | trim != '')
    tags:
    - ruby
    - bundler
    - bundler_assert
-   name: Run Bundler
    bundler:
        state: present
        chdir: "{{ chdir }}"
        clean: "{{ bundler.clean|default('yes') }}"
        gem_path: "{{ bundler.gem_path|default(omit) }}"
        extra_args: "{{ bundler.extra_args|default(omit) }}"
        binstub_directory: "{{ bundler.binstub_directory|default(omit) }}"
        exclude_groups: "{{ bundler.exclude_groups|default(['test','integration','development','openstack','tools']) }}"
    become: "{{ bundler.with_sudo|default(omit) }}"
    tags:
    - ruby
    - bundler
    - bundler_install
-   name: Adjust permissions of binstubs
    file:
        path: "{{ chdir }}/bin"
        recurse: true
        owner: root
        group: root
        mode: 493
        state: directory
    when: bundler.binstub_directory is defined
    become: true
    tags:
    - ruby
    - bundler
    - bundler_permission_binstubs
