-   name: 'Hostname'
    debug: var=ansible_hostname
-   include: list_ec2.yml
    when: (hosts == 'ec2' and ec2 is defined)
-   include: list.yml
-   name: 'Hosts by Distribution'
    group_by: key="distribution_{{ ansible_distribution }}_{{ ansible_distribution_version }}"
