---
#- debug: var=hostvars[inventory_hostname]

- name: Group Hosts by Distribution
  group_by: key="distribution_{{ ansible_distribution }}_{{ ansible_distribution_version }}"

- include: list_ec2.yml
  when: hosts == 'ec2'

- include: list.yml
  when: hosts != 'ec2'
