-   include: switch_apt_mirror.yml
    run_once: yes
    when: (ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu') and (roles.switch_apt_mirror is defined and roles.switch_apt_mirror == True)
    tags: [galaxy, switch_apt_mirror]

-   include: ntp.yml
    run_once: yes
    when: (ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu') and (roles.ntp is defined and roles.ntp == True)
    tags: [galaxy, ntp]

-   include: os_hardening.yml
    run_once: yes
    when: (ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu') and (roles.os_hardening is defined and roles.os_hardening == True)
    tags: [galaxy, os_hardening]

# -   include: unattended_upgrades.yml
#     run_once: yes
#     when: ((roles.unattended_upgrades is defined) and (roles.unattended_upgrades == True))
#     tags: [galaxy, unattended_upgrades]

- name: Playbook for 'https://github.com/jnv/ansible-role-unattended-upgrades'
  hosts: all
  gather_facts: yes
  any_errors_fatal: yes
  become: yes
  when: ((roles.unattended_upgrades is defined) and (roles.unattended_upgrades == True))
  roles:
    - { role: unattended-upgrades }
  vars:
    unattended_origins_patterns:
    - 'origin=Ubuntu,archive=${distro_codename}-security'
    - 'o=Ubuntu,a=${distro_codename}'
    - 'o=Ubuntu,a=${distro_codename}-updates'
    - 'o=Ubuntu,a=${distro_codename}-proposed-updates'
    unattended_automatic_reboot: "{{ unattended_upgrades.automatic_reboot|default('false') }}"
    unattended_mail: "{{ unattended_upgrades.mail|default('false') }}"
    unattended_mail_only_on_error: "{{ unattended_upgrades.mail_only_on_error|default('false') }}"
    unattended_minimal_steps: true
    # unattended_automatic_reboot_time: '07:00'
