---
- name: 'Playbook for https://github.com/ANXS/ntp'
  hosts: "{{ hosts|default(omit) }}"
  gather_facts: yes
  any_errors_fatal: yes
  become: yes
  roles:
      - { role: ntp }
  vars:
      ntp_servers: [ntp.in.xplosion.de]
