---
- name: 'Role: Provision'
  hosts: all
  gather_facts: yes
  any_errors_fatal: yes
  # strategy: "{{ provision.strategy|default('linear') }}"
  roles:
      - { role: bootstrap, when: "'bootstrap' in provision.tasks" }
      - { role: packages, when: "'packages' in provision.tasks" }
      - { role: shell, chdir: "{{ deploy.dest }}", data: "{{ provision }}", when: "'shell' in provision.tasks" }
