---
- name: 'Role: Provision'
  hosts: "{{ hosts|default(omit) }}"
  gather_facts: yes
  any_errors_fatal: yes
  strategy: "{{ provision.strategy|default('linear') }}"
  roles:
      - { role: provision }
