---
- name: Playbook for 'https://github.com/chusiang/switch-apt-mirror.ansible.role'
  hosts: all
  gather_facts: yes
  any_errors_fatal: yes
  become: yes
  roles:
      - { role: switch-apt-mirror }
  vars:
      ubuntu_apt_mirror: 'ftp.hawo.stw.uni-erlangen.de'
      # ubuntu_apt_mirror: 'mirror2.tuxinator.org'
      # ubuntu_apt_mirror: 'archive.ubuntu.com'
