---
- name: Playbook for 'https://github.com/jnv/ansible-role-unattended-upgrades'
  hosts: all
  gather_facts: yes
  any_errors_fatal: yes
  become: yes
  roles:
    - { role: unattended-upgrades }
  vars:
    unattended_origins_patterns:
    - 'origin=Ubuntu,archive=${distro_codename}-security'
    - 'o=Ubuntu,a=${distro_codename}'
    - 'o=Ubuntu,a=${distro_codename}-updates'
    - 'o=Ubuntu,a=${distro_codename}-proposed-updates'
    unattended_automatic_reboot: "{{ unattended_upgrades.automatic_reboot|default('false') }}"
    unattended_mail: "{{ unattended_upgrades.mail|default('false') }}"
    unattended_mail_only_on_error: "{{ unattended_upgrades.mail_only_on_error|default('false') }}"
    unattended_minimal_steps: true
    unattended_automatic_reboot_time: '07:00'
