-   name: Assert on 'data.commands'
    assert:
        that: (data.commands is defined and data.commands is not none and data.commands | trim != '')
-   name: Run shell commands
    raw: '{{ shell_command }}'
    args:
        chdir: '{{ chdir|default(omit) }}'
    with_items: '{{ data.commands }}'
    loop_control:
        loop_var: shell_command
    register: shell_commands
    when: data.commands is defined
    become: '{{ data.with_sudo|default(omit) }}'
    tags:
    - shell
    - shell_commands
